version: '3.9'

services:
  backend:
    container_name: nest-container
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./server/development.env
    volumes:
      - ./server/:/app
      - /app/node_modules
    depends_on: 
      - postgres

  postgres:
    container_name: postgres-container
    image: postgres:14.1-alpine
    env_file:
      - ./server/development.env
    volumes:
      - /var/lib/postgresql/data