version: '3.9'

services:
  postgres_test:
    container_name: postgres-container-test
    image: postgres:14.1-alpine
    env_file:
      - ./server/test.env
    volumes:
      - /var/lib/postgresql/data

  backend:
    container_name: nest-container
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./server/test.env
    volumes:
      - ./server/:/app
      - /app/node_modules
    depends_on: 
      - postgres_test